spring.application.name=rupiahpay
server.port=42069

spring.datasource.url=jdbc:postgresql://localhost:5432/rpay
spring.datasource.username=postgres
spring.datasource.password=udyaa123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# .env
# spring.datasource.password=${MYSQL_PASSWORD}